const sampleTexts = {
    easy: [
        "The quick brown fox jumps over the lazy dog.",
        "Typing practice improves your speed and accuracy over time.",
        "React is a JavaScript library for building user interfaces.",
        "Practice makes perfect, especially when it comes to typing skills.",
        "Learning to type without looking at the keyboard is called touch typing.",
        "Simple sentences help beginners develop basic typing skills.",
        "Regular practice is the key to becoming a proficient typist.",
        "Good posture is important when typing for extended periods.",
        "Typing is an essential skill in today's digital world.",
        "Focus on accuracy first, then gradually increase your speed.",
        "Every great journey starts with a single keystroke.",
        "A computer is only as smart as the person using it.",
        "The home row keys are your foundation for touch typing.",
        "Keep your wrists straight and fingers curved when typing.",
        "Muscle memory develops with consistent daily practice.",
        "Start slowly and build up your typing speed gradually.",
        "Proper lighting reduces eye strain during long typing sessions.",
        "Take regular breaks to prevent repetitive strain injuries.",
        "The alphabet has twenty-six letters from A to Z.",
        "Technology connects people from all around the world today."
    ],
    medium: [
        "Programming is the art of telling another human what one wants the computer to do.",
        "The best way to predict the future is to invent it. Alan Kay said that.",
        "Typing quickly and accurately is an essential skill for modern computer users.",
        "JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript specification.",
        "React uses a virtual DOM to efficiently update the UI when the underlying data changes.",
        "Efficient typing can significantly increase your productivity in various computer-related tasks.",
        "The QWERTY keyboard layout was designed in the 1870s for mechanical typewriters to prevent jamming.",
        "Touch typing involves placing your fingers on the home row keys and typing without looking at the keyboard.",
        "Modern keyboards have evolved from mechanical typewriters but maintain the same basic layout and functionality.",
        "Learning keyboard shortcuts can save time and increase efficiency when working with computer applications.",
        "Web development encompasses both front-end user interface design and back-end server-side programming.",
        "Database management systems organize and store vast amounts of information for quick retrieval and analysis.",
        "Cloud computing allows users to access software and storage resources over the internet from anywhere.",
        "Cybersecurity professionals work tirelessly to protect digital infrastructure from malicious attacks and data breaches.",
        "Machine learning algorithms can identify patterns in large datasets that would be impossible for humans to detect.",
        "Open source software development relies on collaborative efforts from programmers worldwide contributing code freely.",
        "User experience design focuses on creating intuitive interfaces that make technology accessible to everyone.",
        "Mobile applications have transformed how we communicate, work, and access information in our daily lives.",
        "Version control systems like Git help developers track changes and collaborate on code projects effectively.",
        "Software testing ensures that applications function correctly and meet user requirements before public release."
    ],
    hard: [
        "The journey of a thousand miles begins with a single step. Typing efficiently is similar - it starts with learning the correct finger positions.",
        "In computer science, artificial intelligence, sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans.",
        "The World Wide Web (WWW), commonly known as the Web, is an information system where documents and other web resources are identified by Uniform Resource Locators, which may be interlinked by hypertext.",
        "Quantum computing is the use of quantum-mechanical phenomena such as superposition and entanglement to perform computation. Computers that perform quantum computations are known as quantum computers.",
        "The process of developing a structured set of instructions to be followed by a computer or electronic device to perform a specific task or solve a particular problem is called computer programming.",
        "The development of typing skills requires consistent practice and attention to technique, including proper finger placement, posture, and rhythmic keystroke patterns that maximize efficiency and minimize strain.",
        "Neuroplasticity, the brain's ability to reorganize itself by forming new neural connections, plays a crucial role in learning complex motor skills such as touch typing, allowing for improved speed and accuracy over time.",
        "The evolution of human-computer interaction has been significantly influenced by advancements in input methods, from punch cards and mechanical keyboards to touchscreens and voice recognition, each requiring different skill sets and adaptations.",
        "Professional typists often achieve speeds exceeding 100 words per minute through a combination of muscle memory, anticipatory reading, and specialized techniques that minimize unnecessary finger movement and maximize keystroke efficiency.",
        "The integration of ergonomic principles into keyboard design aims to reduce the risk of repetitive strain injuries by promoting natural wrist and hand positions, appropriate key resistance, and optimal key spacing for different hand sizes.",
        "Distributed computing architectures enable processing power to be shared across multiple interconnected systems, allowing for scalable solutions to complex computational problems that exceed the capabilities of individual machines.",
        "Cryptographic protocols safeguard digital communications through mathematical algorithms that transform readable information into encoded formats, ensuring confidentiality, integrity, and authenticity in electronic transactions and data storage.",
        "Bioinformatics represents the intersection of biology, computer science, and statistics, utilizing computational methods to analyze biological data such as DNA sequences, protein structures, and genetic variations to advance medical research.",
        "The paradigm shift toward sustainable technology development emphasizes energy-efficient hardware design, renewable energy sources for data centers, and software optimization techniques that reduce computational resource consumption.",
        "Interdisciplinary collaboration between computer scientists, domain experts, and end-users is essential for developing robust artificial intelligence systems that address real-world challenges while maintaining ethical standards and societal benefits.",
        "Advanced microprocessor architectures incorporate sophisticated features such as branch prediction, out-of-order execution, and cache hierarchies to optimize instruction throughput and minimize memory access latencies in high-performance computing applications.",
        "The philosophical implications of consciousness in artificial systems raise fundamental questions about the nature of intelligence, self-awareness, and the potential emergence of sentient machines that challenge traditional boundaries between human and artificial cognition.",
        "Telecommunications infrastructure evolution from copper wire networks to fiber optic cables and wireless communication protocols has revolutionized global connectivity, enabling instantaneous information exchange across vast geographical distances.",
        "Computational complexity theory provides mathematical frameworks for analyzing algorithm efficiency, classifying problems by their inherent difficulty, and establishing theoretical limits on what can be computed within practical time and space constraints.",
        "Interdisciplinary research in computational neuroscience combines principles from computer science, mathematics, physics, and biology to model brain function, simulate neural networks, and develop brain-computer interfaces that bridge biological and artificial systems."
    ]
};

export default sampleTexts;